# Multiple Regression

In [ ]:
# importing packages
import numpy as np
import pandas as pd
import os

In [2]:
os.chdir(r'C:\Users\Yogesh\Downloads')         #changing the directory

In [3]:
o = pd.read_csv('cars.csv')                   # loading data
o

Car   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0          8         307.0         130   
1            Buick Skylark 320  15.0          8         350.0         165   
2           Plymouth Satellite  18.0          8         318.0         150   
3                AMC Rebel SST  16.0          8         304.0         150   
4                  Ford Torino  17.0          8         302.0         140   
..                         ...   ...        ...           ...         ...   
401            Ford Mustang GL  27.0          4         140.0          86   
402          Volkswagen Pickup  44.0          4          97.0          52   
403              Dodge Rampage  32.0          4         135.0          84   
404                Ford Ranger  28.0          4         120.0          79   
405                 Chevy S-10  31.0          4         119.0          82   

     Weight  Acceleration  Model  Origin  
0      3504          12.0     70      US  
1      3693          11.5     70      US  
2      3436          11.0     70      US  
3      3433          12.0     70      US  
4      3449          10.5     70      US  
..      ...           ...    ...     ...  
401    2790          15.6     82      US  
402    2130          24.6     82  Europe  
403    2295          11.6     82      US  
404    2625          18.6     82      US  
405    2720          19.4     82      US  

[406 rows x 9 columns]

In [4]:
x = o[['Displacement','Horsepower','Weight',]]           #ilocing the data
y = o[['MPG']]

In [5]:
#adding the constant
c = [1]                          #adding the constant
c = c * len(o)

In [6]:
x.insert(0,'Constant',c)        # inserting constant in the datafareme


In [7]:
#xT
ot = x.T                        #Tranpsosing the dataframe 

In [8]:
# xTx 
c = ot.dot(x)                   # multipying the predictor
c

Constant  Displacement   Horsepower        Weight
Constant          406.0  7.908050e+04      42033.0  1.209642e+06
Displacement    79080.5  1.986180e+07    9691666.0  2.691754e+08
Horsepower      42033.0  9.691666e+06    5016637.0  1.369210e+08
Weight        1209642.0  2.691754e+08  136921031.0  3.894578e+09

In [9]:
#[xTx]Inverse
xTxInverse = np.linalg.inv(c)                   #  inverse of the matrix
xTxInverse

array([[ 7.49091050e-02,  2.97046642e-04, -1.51777896e-04,
        -3.84609771e-05],
       [ 2.97046642e-04,  2.17716262e-06, -1.72610351e-06,
        -1.82052819e-07],
       [-1.51777896e-04, -1.72610351e-06,  6.50028263e-06,
        -6.20873162e-08],
       [-3.84609771e-05, -1.82052819e-07, -6.20873162e-08,
         2.69680623e-08]])

In [10]:
#xT
ot

0       1       2       3       4       5       6       7    \
Constant         1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
Displacement   307.0   350.0   318.0   304.0   302.0   429.0   454.0   440.0   
Horsepower     130.0   165.0   150.0   150.0   140.0   198.0   220.0   215.0   
Weight        3504.0  3693.0  3436.0  3433.0  3449.0  4341.0  4354.0  4312.0   

                 8       9    ...     396     397     398     399     400  \
Constant         1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0   
Displacement   455.0   390.0  ...   156.0   232.0   144.0   135.0   151.0   
Horsepower     225.0   190.0  ...    92.0   112.0    96.0    84.0    90.0   
Weight        4425.0  3850.0  ...  2585.0  2835.0  2665.0  2370.0  2950.0   

                 401     402     403     404     405  
Constant         1.0     1.0     1.0     1.0     1.0  
Displacement   140.0    97.0   135.0   120.0   119.0  
Horsepower      86.0    52.0    84.0    79.0    82.0  
Weight        2790.0  2130.0  2295.0  2625.0  2720.0  

[4 rows x 406 columns]

In [12]:
#xTy
h = ot.dot(y)                           # geting dot product product
h
np.array([ 4.44999776e+01, -7.91897363e-03, -3.93767539e-02, -5.31300288e-03])

array([ 4.44999776e+01, -7.91897363e-03, -3.93767539e-02, -5.31300288e-03])

# b = (xTx)-1*xTy

In [13]:
xTxInverse.dot(h)                      #multiupling xTx whit h

array([[ 4.44999776e+01],
       [-7.91897363e-03],
       [-3.93767539e-02],
       [-5.31300288e-03]])

In [14]:
def multiple_pred(d,h,w):                                                                  # defining funtion
    y = 4.44999776e+01 - 7.91897363e-03 * d - 3.93767539e-02 * h - 5.31300288e-03 * w      # adding variable multiple  for predictors
    return(y)

In [15]:
multiple_pred(307,130,3504)                                           #using  mutiple preditor

18.333112597070002

In [ ]:
y = 4.44999776e+01 - 7.91897363e-03 * d - 3.93767539e-02 * h - 5.31300288e-03 * w 

In [21]:
#y predected values in multiple predector
y = 4.44999776e+01 - 7.91897363e-03 * o.Displacement - 3.93767539e-02 * o.Horsepower - 5.31300288e-03 * o.Weight 
y.head(50)

0     18.333113
1     15.610253
2     17.819753
3     17.946558
4     18.271155
5     10.242395
6      9.109063
7      9.639959
8      8.527037
9     13.474934
10    22.501249
11    13.224715
12    14.263121
13    12.442109
14    14.303154
15    15.842733
16    16.332619
17    18.781203
18    15.443671
19    15.641148
20    27.261899
21    24.139492
22    24.366287
23    25.824420
24    28.949987
25    32.171146
26    26.006769
27    27.198143
28    27.317231
29    27.222960
30    25.311362
31     8.663637
32    10.943801
33    10.431047
34     9.351766
35    28.949987
36    27.818775
37    28.026972
38    32.853514
39    31.332633
40    24.730651
41    20.312232
42    20.895572
43    21.511544
44    21.255947
45    12.868743
46    10.724211
47    13.625561
48    14.313171
49     8.053266
dtype: float64